/**
 * Canonical paths for the Terragrunt documentation inventory at upstream
 * revision 2a4802eb604cc7175d9937a9d5303d66656b86ed. The llms.txt generator
 * sorts pages by their Starlight content ID, which is the canonical slug.
 */
export const TERRAGRUNT_DOC_MANIFEST = [
  ['Contributing', '/community/contributing/'],
  ['License', '/community/license/'],
  ['Support', '/community/support/'],
  ['Caching', '/features/caching/'],
  ['Automatic Provider Cache Dir', '/features/caching/auto-provider-cache-dir/'],
  ['Content Addressable Store (CAS)', '/features/caching/cas/'],
  ['Google Cloud Storage', '/features/caching/cas/gcs/'],
  ['Git', '/features/caching/cas/git/'],
  ['HTTP', '/features/caching/cas/http/'],
  ['Local paths', '/features/caching/cas/local/'],
  ['Mercurial', '/features/caching/cas/mercurial/'],
  ['OCI', '/features/caching/cas/oci/'],
  ['OpenTofu/Terraform Registry', '/features/caching/cas/registry/'],
  ['Amazon S3', '/features/caching/cas/s3/'],
  ['SMB', '/features/caching/cas/smb/'],
  ['Provider Cache Server', '/features/caching/provider-cache-server/'],
  ['Catalog', '/features/catalog/'],
  ['Non-interactive catalog', '/features/catalog/non-interactive/'],
  ['Scaffold', '/features/catalog/scaffold/'],
  ['Catalog TUI', '/features/catalog/tui/'],
  ['Overview', '/features/filter/', 'Learn how to use the --filter flag to target specific infrastructure'],
  ['Attribute Expressions', '/features/filter/attributes/'],
  ['Combining Expressions', '/features/filter/combining/'],
  ['Filters File', '/features/filter/filters-file/'],
  ['Git Expressions', '/features/filter/git/'],
  ['Graph Expressions', '/features/filter/graph/'],
  ['Name Expressions', '/features/filter/name/'],
  ['Path Expressions', '/features/filter/path/'],
  ['Stacks', '/features/stacks/'],
  ['Explicit Stacks', '/features/stacks/explicit/'],
  ['Implicit Stacks', '/features/stacks/implicit/'],
  ['Run Queue', '/features/stacks/run-queue/'],
  ['Run Report', '/features/stacks/run-report/'],
  ['Stack Operations', '/features/stacks/stack-operations/'],
  ['Units', '/features/units/'],
  ['Authentication', '/features/units/authentication/'],
  ['Auto-init', '/features/units/auto-init/'],
  ['IaC Engines', '/features/units/engine/'],
  ['Extra Arguments', '/features/units/extra-arguments/'],
  ['Hooks', '/features/units/hooks/'],
  ['Importing Existing Resources', '/features/units/importing/'],
  ['Includes', '/features/units/includes/'],
  ['Lock File Handling', '/features/units/lock-files/'],
  ['OCI Registries', '/features/units/oci/'],
  ['Feature Flags, Errors and Excludes', '/features/units/runtime-control/'],
  ['State Backend', '/features/units/state-backend/'],
  ['Terragrunt Cache', '/features/units/terragrunt-cache/'],
  ['Install', '/getting-started/install/'],
  ['Overview', '/getting-started/overview/', 'Get a high level overview of the most important Terragrunt features.'],
  ['Quick Start', '/getting-started/quick-start/'],
  ['Terminology', '/getting-started/terminology/'],
  ['Introduction', '/guides/ci-with-terragrunt/', 'Introduction to the Continuous Integration with Terragrunt guide'],
  ['Deploying an app', '/guides/ci-with-terragrunt/deploying-an-app/'],
  ['Lessons Learned', '/guides/ci-with-terragrunt/lessons-learned/'],
  ['Prerequisites', '/guides/ci-with-terragrunt/prerequisites/'],
  ['Terragrunt Scale', '/guides/ci-with-terragrunt/terragrunt-scale/', 'Signing up for Terragrunt Scale Free Tier and walking through the onboarding wizards'],
  ["What's next", '/guides/ci-with-terragrunt/whats-next/'],
  ['Terragrunt Patterns', '/guides/patterns/'],
  ['Introduction', '/guides/terralith-to-terragrunt/', 'Introduction to the Terralith to Terragrunt guide'],
  ['Overview', '/guides/terralith-to-terragrunt/overview/', 'Overview of the Terralith to Terragrunt guide'],
  ['Setup', '/guides/terralith-to-terragrunt/setup/'],
  ['Step 1: Starting the Terralith', '/guides/terralith-to-terragrunt/step-1-starting-the-terralith/'],
  ['Step 2: Refactoring', '/guides/terralith-to-terragrunt/step-2-refactoring/'],
  ['Step 3: Adding dev', '/guides/terralith-to-terragrunt/step-3-adding-dev/'],
  ['Step 4: Breaking the Terralith', '/guides/terralith-to-terragrunt/step-4-breaking-the-terralith/'],
  ['Step 5: Adding Terragrunt', '/guides/terralith-to-terragrunt/step-5-adding-terragrunt/'],
  ['Step 6: Breaking the Terralith Further', '/guides/terralith-to-terragrunt/step-6-breaking-the-terralith-further/'],
  ['Step 7: Taking advantage of Terragrunt Stacks', '/guides/terralith-to-terragrunt/step-7-taking-advantage-of-terragrunt-stacks/'],
  ['Step 8: Refactoring state with Terragrunt Stacks', '/guides/terralith-to-terragrunt/step-8-refactoring-state-with-terragrunt-stacks/'],
  ['Wrap Up', '/guides/terralith-to-terragrunt/wrap-up/'],
  ['Bare Include', '/migrate/bare-include/'],
  ['CLI Redesign', '/migrate/cli-redesign/'],
  ['Migrating from Deprecated Attributes', '/migrate/deprecated-attributes/'],
  ['Migrating from root terragrunt.hcl', '/migrate/migrating-from-root-terragrunt-hcl/'],
  ['Migrating from Queue Flags to Filter', '/migrate/queue-to-filter/'],
  ['Terragrunt Stacks', '/migrate/terragrunt-stacks/'],
  ['Upgrading to Terragrunt 0.19.x', '/migrate/upgrading_to_terragrunt_0.19.x/'],
  ['Terragrunt 1.0 Guarantees', '/process/1-0-guarantees/'],
  ['Changelog', '/process/changelog/'],
  ['CLI Rules', '/process/cli-rules/'],
  ['Terragrunt Frequently Asked Questions', '/process/faq/'],
  ['Releases', '/process/releases/'],
  ['Overview', '/reference/cli/', 'Learn how the Terragrunt CLI works'],
  ['bootstrap', '/reference/cli/commands/backend/bootstrap/'],
  ['delete', '/reference/cli/commands/backend/delete/'],
  ['migrate', '/reference/cli/commands/backend/migrate/'],
  ['browse', '/reference/cli/commands/browse/'],
  ['catalog', '/reference/cli/commands/catalog/'],
  ['graph', '/reference/cli/commands/dag/graph/'],
  ['exec', '/reference/cli/commands/exec/'],
  ['find', '/reference/cli/commands/find/'],
  ['fmt', '/reference/cli/commands/hcl/fmt/'],
  ['validate', '/reference/cli/commands/hcl/validate/'],
  ['print', '/reference/cli/commands/info/print/'],
  ['strict', '/reference/cli/commands/info/strict/'],
  ['list', '/reference/cli/commands/list/'],
  ['OpenTofu Shortcuts', '/reference/cli/commands/opentofu-shortcuts/'],
  ['render', '/reference/cli/commands/render/'],
  ['run', '/reference/cli/commands/run/', 'Run OpenTofu/Terraform commands.'],
  ['scaffold', '/reference/cli/commands/scaffold/'],
  ['clean', '/reference/cli/commands/stack/clean/'],
  ['generate', '/reference/cli/commands/stack/generate/'],
  ['output', '/reference/cli/commands/stack/output/'],
  ['run', '/reference/cli/commands/stack/run/', 'Run a command against a stack of units defined in a terragrunt.stack.hcl file.'],
  ['Global Flags', '/reference/cli/global-flags/'],
  ['Experiments', '/reference/experiments/'],
  ['Overview', '/reference/hcl/', 'Learn how to configure Terragrunt'],
  ['Attributes', '/reference/hcl/attributes/'],
  ['Blocks', '/reference/hcl/blocks/'],
  ['Functions', '/reference/hcl/functions/'],
  ['Overview', '/reference/logging/', 'Learn how Terragrunt decides what to log, and when.'],
  ['Formatting', '/reference/logging/formatting/'],
  ['Strict Controls', '/reference/strict-controls/'],
  ['OpenTofu and Terraform Version Compatibility Table', '/reference/supported-versions/'],
  ['Drift Detection', '/terragrunt-scale/drift-detection/'],
  ['Installation', '/terragrunt-scale/installation/'],
  ['Terragrunt Scale', '/terragrunt-scale/overview/', 'GitOps infrastructure pipelines, drift detection, and automated updates for Terragrunt. No black boxes.'],
  ['Patcher', '/terragrunt-scale/patcher/'],
  ['Pipelines', '/terragrunt-scale/pipelines/'],
  ['Terragrunt vs Terragrunt Scale', '/terragrunt-scale/terragrunt-at-scale/'],
  ['Troubleshooting', '/terragrunt-scale/troubleshooting/'],
  ['Debugging', '/troubleshooting/debugging/'],
  ['OpenTelemetry', '/troubleshooting/open-telemetry/'],
  ['Performance', '/troubleshooting/performance/'],
] as const;